set -g default-terminal "xterm-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"
set -g base-index 1
set -g pane-base-index 1

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-restore 'on'

set-environment -g TMUX_PLUGIN_MANAGER_PATH ~/.config/tmux/plugins/
run '~/.config/tmux/plugins/tpm/tpm'

unbind C-b
set -g prefix 'C-a'
bind-key 'C-a' send-prefix

set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xcopy"

bind r source-file ~/.tmux.conf \; display-message "Config reloaded"
