[PTRX]
source = imaps://patrykdev@ptrx.pl:!ZoA8dsZrK@imap.mail.ovh.net:993
outgoing = smtps+plain://patrykdev@ptrx.pl:!ZoA8dsZrK@smtp.mail.ovh.net:465
from = Patryk Ilkiw <patrykdev@ptrx.pl>
copy-to = Sent
default = INBOX
