preload = ~/personal/wallpapers/nissan-gt-r-black-gy-2560x1440.jpg
wallpaper = DisplayPort-1,~/personal/wallpapers/nissan-gt-r-black-gy-2560x1440.jpg
wallpaper = DisplayPort-0,~/personal/wallpapers/nissan-gt-r-black-gy-2560x1440.jpg
